apiVersion: xline.io.datenlord.com/v1alpha1
kind: XlineCluster
metadata:
  labels:
    app.kubernetes.io/name: xlinecluster
    app.kubernetes.io/instance: xlinecluster-sample
    app.kubernetes.io/part-of: xline-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: xline-operator
  name: xlinecluster-sample
spec:
  # TODO(user): Add fields here
